import type { Project } from "@/interface/types"
export const projects: Project[] = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Complete redesign of the company website",
    teamMembers: ["John Doe", "Jane Smith", "Bob Johnson", "Alice Williams"],
    tasks: [
      {
        id: 1,
        title: "Design homepage layout",
        description: "Create wireframes and design for new homepage",
        status: "Review",
        priority: "high",
        assignee: "Jane Smith",
        dueDate: "2025-11-15",
        labels: ["design", "ui"],
        comments: [
          {
            id: 1,
            author: "John Doe",
            content: "Great design! I love the new layout.",
            createdAt: "2025-11-06T10:30:00",
            replies: [
              {
                id: 11,
                author: "Jane Smith",
                content: "Thanks! We spent a lot of time on this.",
                createdAt: "2025-11-06T10:45:00",
              },
            ],
          },
          {
            id: 2,
            author: "Bob Johnson",
            content: "Can we adjust the spacing a bit?",
            image: "/design-mockup.jpg",
            createdAt: "2025-11-06T11:15:00",
            replies: [],
          },
        ],
      },
      {
        id: 2,
        title: "Implement header component",
        description: "Build responsive header with navigation",
        status: "In Progress",
        priority: "high",
        assignee: "John Doe",
        dueDate: "2025-11-10",
        labels: ["frontend", "component"],
        comments: [],
      },
      {
        id: 3,
        title: "Create footer section",
        description: "Design and implement footer with links",
        status: "To Do",
        priority: "medium",
        assignee: "Bob Johnson",
        dueDate: "2025-11-20",
        labels: ["frontend"],
        comments: [],
      },
      {
        id: 4,
        title: "Setup deployment pipeline",
        description: "Configure CI/CD for new design",
        status: "Done",
        priority: "medium",
        assignee: "Alice Williams",
        dueDate: "2025-11-05",
        labels: ["devops", "deployment"],
        comments: [],
      },
    ],
  },
  {
    id: 2,
    name: "Mobile App Development",
    description: "Native iOS and Android app",
    teamMembers: ["John Doe", "Bob Johnson"],
    tasks: [
      {
        id: 5,
        title: "Setup React Native project",
        description: "Initialize project and configure dev environment",
        status: "Done",
        priority: "high",
        assignee: "John Doe",
        dueDate: "2025-11-01",
        labels: ["setup", "mobile"],
        comments: [],
      },
      {
        id: 6,
        title: "Create login screen",
        description: "Build authentication UI",
        status: "In Progress",
        priority: "high",
        assignee: "Bob Johnson",
        dueDate: "2025-11-12",
        labels: ["mobile", "auth"],
        comments: [],
      },
    ],
  },
]