
export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/Auth/login',
    REGISTER: '/api/Auth',
    GET_ALL_USERS: '/api/Auth',
    SEARCH_USERS: '/api/Auth/search',
    GET_USER: (id: number) => `/api/Auth/${id}`,
    UPDATE_USER: (id: number) => `/api/Auth/${id}`,
    DELETE_USER: (id: number) => `/api/Auth/${id}`,
  },
  PROJECT: {
    LIST: '/api/Project',
    GET_BY_ID: (id: number) => `/api/Project/${id}`,
    MY_PROJECTS: '/api/Project/my-projects',
    CREATE: '/api/Project',
    UPDATE: (id: number) => `/api/Project/${id}`,
    DELETE: (id: number) => `/api/Project/${id}`,
  },
  BOARD: {
    GET_BOARD: (boardId: number) => `/api/boards/${boardId}`,
    GET_TASKS: (boardId: number) => `/api/boards/${boardId}/tasks`,
    CREATE_SPRINT: (boardId: number) => `/api/boards/${boardId}/sprints`,
    GET_SPRINT: (sprintId: number) => `/api/boards/sprints/${sprintId}`,
    ADD_TASKS_TO_SPRINT: (sprintId: number) => `/api/boards/sprints/${sprintId}/tasks`,
    UPDATE_TASK_POSITION: () => `/api/boards/tasks/position`,
    REORDER_COLUMN: (columnId: number, boardId: number) => `/api/boards/columns/${columnId}/reorder?boardId=${boardId}`,
  },
  TASK: {
    CREATE: (projectId: number) => `/api/projects/${projectId}/issues`,
    GET_DETAIL: (projectId: number, taskId: number) => `/api/projects/${projectId}/issues/${taskId}`,
    UPDATE: (projectId: number, taskId: number) => `/api/projects/${projectId}/issues/${taskId}`,
    DELETE: (projectId: number, taskId: number) => `/api/projects/${projectId}/issues/${taskId}`,
    GET_KANBAN: (projectId: number) => `/api/projects/${projectId}/issues`,
    UPDATE_STATUS: (projectId: number, taskId: number) => `/api/projects/${projectId}/issues/${taskId}/status`,
  },
  COMMENT: {
    CREATE: (projectId: number, issueId: number) => `/api/projects/${projectId}/issues/${issueId}/comments`,
    GET_ALL: (projectId: number, issueId: number) => `/api/projects/${projectId}/issues/${issueId}/comments`,
    GET_BY_ID: (projectId: number, issueId: number, commentId: number) => `/api/projects/${projectId}/issues/${issueId}/comments/${commentId}`,
    UPDATE: (projectId: number, issueId: number, commentId: number) => `/api/projects/${projectId}/issues/${issueId}/comments/${commentId}`,
    DELETE: (projectId: number, issueId: number, commentId: number) => `/api/projects/${projectId}/issues/${issueId}/comments/${commentId}`,
  },
  TEAM: {
    LIST: '/api/Team',
    GET_BY_ID: (id: number) => `/api/Team/${id}`,
    CREATE: '/api/Team',
    UPDATE: (id: number) => `/api/Team/${id}`,
    DELETE: (id: number) => `/api/Team/${id}`,
    ADD_MEMBER: (id: number) => `/api/Team/${id}/members`,
    REMOVE_MEMBER: (id: number, userId: number) => `/api/Team/${id}/members/${userId}`,
  },
  DEPARTMENT: {
    LIST: '/api/departments',
    GET_BY_ID: (id: number) => `/api/departments/${id}`,
    CREATE: '/api/departments',
    UPDATE: (id: number) => `/api/departments/${id}`,
    DELETE: (id: number) => `/api/departments/${id}`,
    GET_ROLES: (id: number) => `/api/departments/${id}/roles`,
    ASSIGN_ROLES: (id: number) => `/api/departments/${id}/roles`,
  },
  DASHBOARD: {
    PROJECT_PROGRESS: (projectId: number) => `/api/dashboard/projects/${projectId}/progress`,
    PROJECT_SUMMARY: (projectId: number) => `/api/dashboard/projects/${projectId}/summary`,
    ALL_PROJECTS: '/api/dashboard/projects/all',
    USER_TASKS: '/api/dashboard/users',
    ALL_USERS: '/api/dashboard/all-users',
    MY_DAY_STATISTICS: (userId: number) => `/api/dashboard/my-day/statistics/${userId}`,
  },
  EMAIL: {
    SEND_TEST: '/api/Email/test',
    STATUS: '/api/Email/status',
  },
} as const;